name: Python Unit Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Create virtualenv
        run: |
          python -m venv tweet-venv
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          python -m pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        env:
          API_KEY: ${{secrets.API_KEY}}
          API_SECRET_KEY: ${{secrets.API_SECRET_KEY}}
          BEARER_TOKEN: ${{secrets.BEARER_TOKEN}}
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
        run: |
          python -m pip install pytest
          pytest
